name: 'Run PMTK script'
description: 'A custom GitHub Action that runs the PMTK powershell script'
inputs:
  FilePath:
    description: 'The path to the config file including the name'
    required: true
  WorkingDirectory:
    description: 'The parent directory of the customer update directories'
    required: true  
  ISSUE_PAT:
    description: 'A personal access token for creating issue comments'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: run.ps1 -ConfigFilePath ${{ inputs.FilePath }} -WorkingDirectory ${{ inputs.WorkingDirectory }}
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.ISSUE_PAT }}
