name: 'Run PMTK script'
description: 'A custom GitHub Action that runs the PMTK powershell script'
inputs:
  FilePath:
    description: 'An input for the custom action'
    required: true
    default: 'default value'
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: pmtk.ps1 -ConfigFilePath ${{ inputs.FilePath }}
      shell: pwsh
